module.exports = {
  AUTH_REQUIRED: 'Авторизация не выполнена',
  AUTH_FAILED: 'Ошибка авторизации',
  EMAIL_REQUIRED: 'Необходимо ввести почту',
  NAME_REQUIRED: 'Необходимо ввести имя',
  PASS_REQUIRED: 'Необходимо ввести пароль',
  NO_KEYWORD: 'Отсутствует keyword',
  NO_TITLE: 'Отсутствует title',
  NO_TEXT: 'Отсутствует text',
  NO_DATE: 'Отсутствует date',
  NO_SOURCE: 'Отсутствует source',
  NO_LINK: 'Отсутствует link',
  NO_IMAGE: 'Отсутствует image',
  NO_ARTICLEID: 'Отсутствует articleId',
  ARTICLES_NOT_FOUND: 'Статьи не найдены',
  ARTICLE_NOT_FOUND: 'Статья не найдена',
  NO_PERMISSIONS: 'Нет прав на удаление чужой статьи',
  USER_NOT_FOUND: 'Пользователь не найден',
  SERVER_ERROR: 'Произошла ошибка на сервере',
  EMAIL_ALREADY_USED: 'Такой пользователь уже есть',
  WRONG_EMAIL: 'Неверный формат почты',
  WRONG_EMAIL_OR_PASSWORD: 'Неправильные почта или пароль',
  WRONG_URL: 'Неверный формат ссылки',
  URL_NOT_FOUND: 'Запрашиваемый ресурс не найден',
  APP_ON: 'App listening on port',
};
